export const listArticle = [
   {
      id: 1,
      title: `Daftar Makanan yang Punya Kalori Tinggi 'Tersembunyi', Bisa Bikin Gagal Diet`,
      link: 'https://health.detik.com/diet/d-7169881/daftar-makanan-yang-punya-kalori-tinggi-tersembunyi-bisa-bikin-gagal-diet',
      category: 'all',
   },
   {
      id: 2,
      title: `Menu Sarapan untuk Menghilangkan Perut Buncit`,
      link: 'https://health.detik.com/diet/d-7168672/7-menu-sarapan-untuk-menghilangkan-perut-buncit',
      category: 'Gemuk',
   },
   {
      id: 3,
      title: `4 Tips Turun BB Tanpa Nyiksa ala Ahli Gizi, Cocok Buat Pemula`,
      link: 'https://health.detik.com/diet/d-7160565/4-tips-turun-bb-tanpa-nyiksa-ala-ahli-gizi-cocok-buat-pemula',
      category: 'Gemuk',
   },
   {
      id: 4,
      title: `Diet Masih Makan Nasi? Nggak Masalah! Bisa Kok Turun BB, Asalkan ...`,
      link: 'https://health.detik.com/diet/d-7148316/diet-masih-makan-nasi-nggak-masalah-bisa-kok-turun-bb-asalkan',
      category: 'all',
   },
   {
      id: 5,
      title: `Olahraga di Tengah Cuaca Tak Menentu, Menyehatkan atau Cari Penyakit?`,
      link: 'https://health.detik.com/kebugaran/d-7164698/olahraga-di-tengah-cuaca-tak-menentu-menyehatkan-atau-cari-penyakit',
      category: 'all',
   },
   {
      id: 6,
      title: `Jangan Anggap Enteng, Sebesar Ini Manfaat Jalan Kaki 10 Menit Tiap Hari`,
      link: 'https://health.detik.com/kebugaran/d-7143045/jangan-anggap-enteng-sebesar-ini-manfaat-jalan-kaki-10-menit-tiap-hari',
      category: 'all',
   },
   {
      id: 7,
      title: `5 Olahraga yang Memperlambat Penuaan, Terbukti Ampuh Bikin Awet Muda!`,
      link: 'https://health.detik.com/kebugaran/d-7047353/5-olahraga-yang-memperlambat-penuaan-terbukti-ampuh-bikin-awet-muda',
      category: 'all',
   },
   {
      id: 8,
      title: `Tips Makan Sehat Agar Resolusi Gaya Hidup Sehat Mudah Dijalani`,
      link: 'https://food.detik.com/info-sehat/d-5885849/5-tips-makan-sehat-agar-resolusi-gaya-hidup-sehat-mudah-dijalani',
      category: 'Normal (Ideal)',
   },
   {
      id: 9,
      title: `Manfaat Olahraga yang Dilakukan Secara Teratur terhadap Kesehatan `,
      link: 'https://health.detik.com/berita-detikhealth/d-5218823/7-manfaat-olahraga-untuk-kesehatan-yang-dilakukan-secara-teratur',
      category: 'Normal (Ideal)',
   },
   {
      id: 10,
      title: `Jangan Sepelekan, Ini Pentingnya Serat untuk Pencernaan Anda`,
      link: 'https://health.detik.com/berita-detikhealth/d-5073719/jangan-sepelekan-ini-pentingnya-serat-untuk-pencernaan-anda',
      category: 'Normal (Ideal)',
   },
   {
      id: 11,
      title: `21 Makanan Penambah Berat Badan yang Aman dan Sehat`,
      link: 'https://www.detik.com/bali/berita/d-6475095/21-makanan-penambah-berat-badan-yang-aman-dan-sehat',
      category: 'Kurus',
   },
   {
      id: 12,
      title: `Buat yang Kerempeng, 5 Makanan Sehat Ini Ampuh Menambah Berat Badan`,
      link: 'https://health.detik.com/diet/d-5251552/buat-yang-kerempeng-5-makanan-sehat-ini-ampuh-menambah-berat-badan',
      category: 'Kurus',
   },
   {
      id: 13,
      title: `Olahraga Juga Bisa Naikkan Berat Badan Lho`,
      link: 'https://health.detik.com/hidup-sehat-detikhealth/d-2147048/olahraga-juga-bisa-naikkan-berat-badan-lho',
      category: 'Kurus',
   },
   {
      id: 14,
      title: `10 Cara Diet Sehat Cepat dan Aman untuk Turunakn Berat Badan`,
      link: 'https://www.detik.com/bali/berita/d-6508754/10-cara-diet-sehat-cepat-dan-aman-untuk-turunkan-berat-badan',
      category: 'Gemuk',
   },
   {
      id: 15,
      title: `17 Manfaat Minum Air Putih bagi Kesehatan Tubuh`,
      link: 'https://health.detik.com/kebugaran/d-6505885/17-manfaat-minum-air-putih-bagi-kesehatan-tubuh',
      category: 'all',
   },
   {
      id: 16,
      title: `Manfaat Puasa bagi Tubuh, Bisa Bantu Turunkan Berat Badan lho!`,
      link: 'https://www.detik.com/sumut/berita/d-6637513/13-manfaat-puasa-bagi-tubuh-bisa-bantu-turunkan-berat-badan-lho',
      category: 'all',
   },
   {
      id: 17,
      title: `Mengenal Obesitas, Catat Definisi dan Faktor Penyebabnya`,
      link: 'https://www.detik.com/jatim/berita/d-6157160/mengenal-obesitas-catat-definisi-dan-faktor-penyebabnya',
      category: 'Kegemukan (Obesitas)',
   },
   {
      id: 18,
      title: `Sederet Penyakit yang Muncul karena Obesitas`,
      link: 'https://20.detik.com/e-flash/20210324-210324106/sederet-penyakit-yang-muncul-karena-obesitas',
      category: 'Kegemukan (Obesitas)',
   },
   {
      id: 19,
      title: `Kegemukan di Bawah Usia 40 Tahun, Tingkatkan Risiko Kanker`,
      link: 'https://health.detik.com/berita-detikhealth/d-4743981/kegemukan-di-bawah-usia-40-tahun-tingkatkan-risiko-kanker',
      category: 'Kegemukan (Obesitas)',
   },
]